import numpy as np

WSG84_SEMI_MAJOR_AXIS = np.float64(6_378_137)
WSG84_SEMI_MINOR_AXIS = np.float64(6_356_752.314_245)

DISTANCE_PRECISION = 0.1 # m

# See https://wiki.openstreetmap.org/wiki/Precision_of_coordinates
LATITUDE_PRECISION = 1e-7
LONGITUDE_PRECISION = 1e-7
HEIGHT_PRECISION = DISTANCE_PRECISION

AZIMUTH_PRECISION = 1e-5
ELEVATION_PRECISION = 1e-5
RANGE_PRECISION = DISTANCE_PRECISION

TIME_PRECISION = 1e-9 # 1ns